name: ci
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        builder:
          - dune
          - make
          - make-no-magic
        ocaml-compiler:
          - 4.00.x
          - 4.01.x
          - 4.02.x
          - 4.03.x
          - 4.04.x
          - 4.05.x
          - 4.06.x
          - 4.07.x
          - 4.08.x
          - 4.09.x
          - 4.10.x
          - 4.11.x
          - 4.12.x
          - 4.13.x
          - 4.14.x
        exclude:
          - builder: dune
            ocaml-compiler: 4.00.x
          - builder: dune
            ocaml-compiler: 4.01.x
      matrix:
        os:
          - macos-latest
          - windows-latest
        builder:
          - dune
          - make
          - make-no-magic
        ocaml-compiler:
          - 4.02.x
          - 4.14.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Make stdcompat
        run: opam exec -- sh -exc ".github/scripts/build-${{ matrix.builder }}.sh"
